- src/App.js
- src/components/Header.js
- src/context/MealsContext.js
- src/context/MyProvider.js
- src/index.js
- src/pages/Comidas.js
- src/pages/Login.js
- src/services/drinksAPI.js
- src/services/mealsAPI.js
Configurações da estrutura inicial da aplicação.
> Grupo 13 - Configurações iniciais do projeto.

- README.md
- src/context/Provider.js
- src/pages/Comidas.jsx
- src/pages/Login.jsx
- src/pages/Rotas.jsx
Arrumando Lint e passando nos requisitos 2 ao 8 da Tela de Login
> [GRUPO 04] Tela de Login - Passando requisitos 2 ao 8

- src/App.js
- src/App.test.js
- src/context/LoginContext.js
- src/context/LoginProvider.js
- src/index.js
- src/pages/Foods.js
- src/pages/Login.js
- src/renderWithRouter.js
Comecando o ultimo projeto do bloco de front-end!
> add Context, Login.js

- package-lock.json
- package.json
- src/services/index.js
Implemented services index file with API call functions
> Requisito 15 - Implemented services index file

- src/context/MyProvider.js
- src/services/drinksAPI.js
> Grupo 13 - Finalizado estrutura Inicial

- src/App.js
- src/App.test.js
- src/components/Header.js
- src/css/Header.css
- src/pages/Bebidas.js
- src/pages/Comidas.js
- src/tests/Comidas.test.js
- src/tests/Login.test.js
Adicionei um Header que funciona para main pages, o título é passado através de props.
Fiz o teste para implementação da página de comidas.
Implementei testes para o comportamento do botão de login (Enviar para página de comidas)
Implementei página de comidas e bebidas.
CSS do header está pronto (Cores só coloquei para exemplificar)
> [Group 9] Requisito 9 com eSLint, Tests, CSS.

- .eslintrc.json
- README.md
- package-lock.json
- package.json
- src/App.js
- src/App.test.js
- src/helpers/renderWithRouter.js
- src/helpers/testConfig.js
- src/index.js
- src/pages/Food.js
- src/pages/Login.js
- src/redux/actions/LoginActions.js
- src/redux/reducers/loginReducer.js
- src/redux/store.js
Adding redux configuration
adding tests to login page
adding components folder
adding pages folder
adding login page
adding helpers folder
adding tests.config.js to helpers
adding renderWithrouter to helpers
> Main group12 redux basic structure

- src/components/Header.jsx
- src/components/Login.jsx
- src/hooks/Provider.jsx
- src/pages/Comidas.jsx
- src/pages/Profile.jsx
implement req 12 and fix lint issue in all project
> implement req 12 and fix lint issues

- src/components/Header.css
- src/components/Header.js
- src/components/SearchBar.js
- src/context/ReceitasContext.js
- src/context/ReceitasProvider.js
- src/pages/Comidas.js
- src/pages/Explorar.js
- src/pages/Perfil.js
> [Main group 11] header-component

- package-lock.json
- package.json
- src/components/SearchBar.jsx
- src/context/ReceitasProvider.jsx
- src/pages/Bebidas.jsx
- src/pages/Comidas.jsx
- src/pages/Explorar.jsx
- src/servicesAPI/drinkAPI.js
- src/servicesAPI/foodAPI.js
> [GROUP - 20] Requirement FETCH

- src/components/BotoesFiltrar.js
- src/components/ComidaCard.js
- src/components/Footer.js
- src/context/ReceitasProvider.js
- src/index.js
- src/pages/Comidas.js
- src/service/foodApi.js
Criei pasta service com a API de comida utilizada...
> Main group 11 listadereceitas

- src/Components/Header.jsx
- src/Components/Lupa.jsx
- src/Components/SearchBar.jsx
- src/context/Provider.js
- src/pages/Bebidas.jsx
- src/pages/Comidas.jsx
- src/pages/DetalhesBebidas.jsx
- src/pages/DetalhesComidas.jsx
- src/pages/Explorar.jsx
- src/pages/ExplorarBebidas.jsx
- src/pages/ExplorarBebidasIngredientes.jsx
- src/pages/ExplorarComidas.jsx
- src/pages/ExplorarComidasIngredientes.jsx
- src/pages/ExplorarComidasLocalOrigem.jsx
- src/pages/Login.jsx
- src/pages/Perfil.jsx
- src/pages/ProcessoBebidas.jsx
- src/pages/ProcessoComidas.jsx
- src/pages/ReceitasFavoritas.jsx
- src/pages/ReceitasFeitas.jsx
- src/pages/Rotas.jsx
Requisitos 9 e 11 completos, alguns subrequisitos do 10 e ainda verificar o requisito 12. Talvez passe algum requisito da tela de Perfil.
> [GRUPO 4] Passando requisito 9 e 11 e talvez mais algum bônus

- src/components/Header.js
- src/components/NavigationMenu.js
- src/hooks/useRequestDrink.js
- src/hooks/useRequestFood.js
- src/index.css
- src/pages/Drink.js
- src/pages/Food.js
- src/provider/AppProvider.js
> Main group 14 requirement 25 27

- debug.log
- src/App.css
- src/App.js
- src/components/Card.jsx
- src/components/Header.jsx
- src/components/SearchBar.jsx
- src/context/ReceitasProvider.jsx
- src/pages/Bebidas.jsx
- src/pages/Comidas.jsx
- src/pages/Explorar.jsx
- src/pages/ExplorarComidas.jsx
- src/pages/ExplorarComidasPorLocalOrigem.jsx
- src/pages/Perfil.jsx
- src/servicesAPI/drinkAPI.js
- src/servicesAPI/foodAPI.js
- src/stylesCSS/Card.css
adicionei os cards dos requisitos 25 em diante porem apenas em comidas.jsx e sem os data-testids
> [GROUP - 20] Card - LEIA A DESCRIÇÃO

- public/index.html
- src/context/RecipesAppProvider.js
- src/pages/Bebidas.js
- src/pages/Drinks.js
- src/pages/Foods.js
- src/pages/Home.js
- src/pages/RecipeFoodDetails.js
- src/routes/index.js
- src/services/index.js
Criado a logica de renderização dos cards com os dados da API
> Requisito 16

- src/context/Provider.js
- src/pages/Foods.js
- src/services/ApiFirstLetter.js
- src/services/ApiIngredient.js
- src/services/ApiName.js
- src/services/ApiPageFoods.js
- src/useEffect/useApi.js
> FEAT: creating api foods

- src/components/Footer/Footer.css
- src/components/Footer/Footer.jsx
- src/components/Header/Header.css
- src/components/Header/Header.jsx
- src/components/RecipeCard/RecipeCard.css
- src/components/Recipes/Recipes.css
- src/pages/Explore/Explore.css
- src/pages/Explore/Explore.jsx
- src/pages/Home/Home.css
- src/pages/Home/Home.jsx
..and some general css to display better in mobile
> [GROUP 10] feat: 67, 68 && 69..

- src/App.js
- src/components/Card.jsx
- src/components/SearchBar.jsx
- src/pages/BebidaDetalhada.jsx
- src/pages/Bebidas.jsx
- src/pages/ComidaDetalhada.jsx
- src/pages/Comidas.jsx
- src/servicesAPI/drinkAPI.js
- src/servicesAPI/foodAPI.js
erro na pagina de bebidas do requisito 16
> [GROUP - 20] requisito 15

- src/test/HeaderSearchBar.test.js
> Correcting tests

- src/App.js
- src/index.css
- src/pages/Drink.js
- src/pages/DrinkDetails.js
- src/pages/Food.js
- src/pages/FoodDetails.js
> Main group 14 requirement 32 39

- cypress/integration/header_spec.js
- src/components/Footer.js
- src/pages/Home.js
**Req 20 ainda não passa pois precisa desenvolver mais  a aplicação.**
> Footer implemented

- cypress/integration/header_spec.js
- src/components/Card.js
- src/context/RecipesAppProvider.js
- src/pages/Drinks.js
- src/pages/Foods.js
- src/pages/Home.js
Main group 23 req25 26 implementing elements recipes screen
> Req. 25 - 26

- src/components/MainDrinkCards.js
- src/components/MainFoodCards.js
- src/components/SearchBar.js
- src/provider/RecipesProvider.js
> Main group 18 requisito 18

- src/test/Footer.test.js
- src/test/Header.test.js
- src/test/HeaderSearchBar.test.js
> Main group 14 testing coverage

- src/pages/DoneRecipes/DoneRecipes.jsx
Atualizando para recuperar os requisitos já feitos
> [GROUP 10] branch update

- src/components/header/SearchButton.js
- src/components/header/index.js
- src/libs/capitilizeFirstLetter.js
- src/pages/Explore.js
- src/pages/ExploreDrinks.js
- src/pages/ExploreFoods.js
- src/pages/ExploreMealsOrDrinks.js
- src/pages/Home.js
- src/routes/index.js
- src/services/index.js
Engloba os requisitos **70 ao 73**.
> Main group 23 explore foods drinks

- src/components/FavDrinkCard.js
- src/components/FavFoodCard.js
- src/components/index.js
- src/pages/FavoriteRecipes.js
> favorite screen

- src/pages/Perfil.js
Check if localStorage is not null
> [Main group 11] - Profile page fix

- public/index.html
- src/App.css
- src/App.js
- src/pages/DrinkDetails.js
- src/pages/DrinkInProgress.js
- src/pages/FoodDetails.js
- src/pages/FoodInProgress.js
- src/provider/RecipesProvider.js
- src/services/FetchApiDrink.js
- src/services/FetchApiFood.js
> :goberserk:

- src/pages/Explorar.js
- src/pages/ExplorarBebidas.js
- src/pages/ExplorarComidas.js
- src/services/FetchApiBebidas.js
- src/services/FetchApiComidas.js
> Group 5 - tela explorar

- cypress/integration/recipe_detail_spec.js
- src/App.css
- src/App.js
- src/components/Categories.jsx
- src/components/Recomended.jsx
- src/context/ReceitasProvider.jsx
- src/pages/BebidaDetalhada.jsx
- src/pages/BebidaEmProgresso.jsx
- src/pages/ComidaDetalhada.jsx
- src/pages/ComidaEmProgresso.jsx
- src/pages/Comidas.jsx
- src/stylesCSS/DetalhesResponsive.css
- src/stylesCSS/PageDetalhada.css
- src/stylesCSS/Recomended.css
> [GROUP - 20] iniciado receitas

- cypress/integration/recipe_detail_spec.js
- src/pages/RecipeDrinkDetails.js
- src/pages/RecipeFoodDetails.js
passando os requisito 33 ao 37
> Main group 23 req36

- .github/workflows/main.yml
- README.md
- cypress/integration/profile_spec.js
- cypress/integration/recipe_detail_spec.js
- src/pages/Perfil.jsx
Requisitos do perfil - 82 ao 87
> [GROUP - 20] Perfil

- cypress/integration/explore_drinks_or_meals_spec.js
- src/pages/ExplorarBebidas.jsx
- src/pages/ExplorarComidas.jsx
- src/servicesAPI/drinkAPI.js
- src/servicesAPI/foodAPI.js
Requisitos das pags de explorar
> [GROUP - 20] Explorar Bebidas e Comidas

- src/pages/Explorar.jsx
- src/styles/Explorar.css
implementa os requisitos da label `explorar`
> Main group 19 requeriment 67-69

- cypress/integration/done_recipes_spec.js
- cypress/integration/explore_by_area_spec.js
- cypress/integration/explore_by_ingredient_spec.js
- cypress/integration/explore_spec.js
- cypress/integration/recipe_in_progress_spec.js
- src/App.js
- src/components/Card.jsx
- src/context/ReceitasProvider.jsx
- src/pages/Bebidas.jsx
- src/pages/Comidas.jsx
- src/pages/ExplorarBebidas.jsx
- src/pages/ExplorarBebidasIngredientes.jsx
- src/pages/ExplorarComidas.jsx
- src/pages/ExplorarComidasIngredientes.jsx
- src/pages/ExplorarComidasPorLocalOrigem.jsx
- src/pages/NotFound.jsx
- src/pages/Perfil.jsx
- src/pages/index.jsx
- src/servicesAPI/drinkAPI.js
- src/servicesAPI/foodAPI.js
> [GROUP - 20] Explorar por ingredientes

- src/App.js
- src/components/RecipesList.js
- src/pages/CockTail.js
- src/pages/ExploreFoodByArea.js
- src/pages/Food.js
- src/redux/reducers/sitemap.js
> Main group 12 fetch api

- src/pages/DrinkInProgress.js
- src/pages/FoodInProgress.js
> Evaluator crazy 4!

- src/App.css
- src/components/ShareBtn.js
- src/pages/DrinkInProgress.js
- src/pages/FinishedRecipes.js
- src/pages/FoodInProgress.js
Requirements done, tests to do
> Main group 14 requeriment 54 59

- src/pages/Perfil.js
Implementei os requisitos do 82 ao 87
> Implementação da Tela de Perfil

- src/pages/Perfil.js
> Feature 83

- src/components/SearchBar.js
- src/context/RecipesAppProvider.js
- src/pages/DrinksPage/DrinksPage.js
- src/pages/RecipesPage/MealsPage.js
- src/services/cocktailAPI.js
[Main Group 1] - Abrindo o PR do SearchBar
> [Main Group 1] - Abrindo o PR do SearchBar

- .eslintrc.json
- src/pages/DrinkInProgress.js
- src/pages/ExploreDrinkIngredients.js
- src/pages/ExploreFoodIngredients.js
> Main group 14 error

- src/components/CardFavorite.jsx
- src/pages/ReceitasFavoritas.jsx
- src/pages/ReceitasFeitas.jsx
Setado todos os data testId's agr precisa do localStorage e das funções de filtro!!!
> [GROUP - 20] Receitas Feitas e Favoritas

- src/App.js
- src/components/Recipes/Recipes.jsx
- src/context/Provider.js
- src/pages/ExploreByArea/ExploreByArea.css
- src/pages/ExploreByArea/ExploreByArea.jsx
- src/pages/ExploreByArea/index.js
- src/pages/NotFound/NotFound.css
- src/pages/NotFound/NotFound.jsx
- src/pages/NotFound/index.js
- src/services/API.js
> [GROUP 10] explore by area

- src/css/details.css
- src/pages/FoodDetail.js
- src/pages/Perfil.js
adicionando requisitos 36 e 37
> Main group 12 requirement 36

- src/components/DrinkCategoriesButtons.js
- src/components/FoodCategoriesButtons.js
- src/components/RecipeCard.js
- src/components/RecipesList.js
- src/components/SearchRecipes.js
- src/helpers/APIRequests.js
- src/helpers/effects/useFetch.js
- src/pages/CockTail.js
- src/pages/Food.js
- src/redux/actions/searchRecipes.js
- src/redux/reducers/searchRecipes.js
- src/redux/reducers/sitemap.js
change recipes fething now is via redux-thunk
change recipes categories initial state at redux
added filters by category type at food and drinks page
> adding requisits 25 to 32

- src/App.test.js
- src/components/Header.js
- src/components/Search.js
- src/tests/02HeaderTest/Requisite09.test.js
- src/tests/02HeaderTest/Requisite10.test.js
- src/tests/02HeaderTest/Requisite11.test.js
- src/tests/02HeaderTest/Requisite12.test.js
- src/tests/renderWithRouter/renderWithRouter2.js
> Main group 24 test req 09 12

- src/components/FavoriteBtn.js
- src/pages/FavoritesRecipes.js
- src/test/Footer.test.js
- src/test/Header.test.js
- src/test/RecipesInProgress.test.js
> Main group 14 final

- src/pages/Foods.js
> Merge conflict resolves and foods card review

- src/Components/Explore.jsx
- src/Pages/ExplorarBebidas.jsx
- src/Pages/ExplorarComidas.jsx
> Main group 17 explorar comidas/bebidas

- src/pages/ProcessoBebidas.jsx
- src/pages/ProcessoComidas.jsx
- src/pages/styles/pages.css
Fiquei com medo de dar o git pull e acabar zoando as mudanças de hoje, entao abri essa branch :D
> [GRUPO 4]Passando alguns requisitos

- src/App.js
- src/css/recipeProgress.css
- src/helpers/assets.js
- src/pages/FoodDetail.js
- src/pages/Perfil.js
- src/pages/RecipeInProgress.js
- src/redux/actions/searchRecipes.js
- src/redux/reducers/searchRecipes.js
> Main group 12 requirement 41

- cypress/integration/explore_by_ingredient_spec.js
- src/App.js
- src/components/ButtonsExploreRecipes.js
- src/components/DrinkCategoriesButtons.js
- src/components/FoodCategoriesButtons.js
- src/components/Footer.jsx
- src/components/Header.js
- src/components/IngredientCard.js
- src/components/RecipesList.js
- src/helpers/APIRequests.js
- src/pages/CockTail.js
- src/pages/Explore.js
- src/pages/ExploreDrink.js
- src/pages/ExploreDrinkByIngredients.js
- src/pages/ExploreFood.js
- src/pages/ExploreFoodByIngredients.js
- src/pages/Food.js
- src/pages/FoodDetail.js
- src/pages/Perfil.js
- src/pages/RecipeInProgress.js
- src/redux/actions/searchRecipes.js
- src/redux/reducers/searchRecipes.js
- src/redux/reducers/sitemap.js
adding requirement 75,76,77
fixing fetchImage using SRC.
> Main group 12 req75 explore by ingredients

- src/App.js
- src/pages/Explore.js
- src/pages/FoodDetail.js
- src/pages/Perfil.js
- src/pages/RecipeInProgress.js
- src/redux/actions/searchRecipes.js
- src/redux/reducers/searchRecipes.js
adding buttons to explore food and drinks with the correct pathname
> Main group 12 requirement 67

- src/context/ReceitasProvider.jsx
- src/pages/Bebidas.jsx
- src/pages/Comidas.jsx
- src/pages/ExplorarBebidasIngredientes.jsx
- src/pages/ExplorarComidasIngredientes.jsx
Adicionada a logica de filtrar por ingredientes!
> [GROUP - 20] Filtro por Ingredientes

- src/components/Card.js
- src/components/explore/ExploreCard.js
- src/context/RecipesAppProvider.js
- src/pages/ExploreDrinkIngredients.js
- src/pages/ExploreFoodIngredients.js
- src/pages/ExploreIngredients.js
- src/pages/Foods.js
- src/routes/index.js
- src/services/index.js
> Main group 23 explore ingredients

- src/pages/Comidas.jsx
- src/tests/App.test.js
- src/tests/Bebidas.test.js
- src/tests/Comidas.test.js
- src/tests/Footer.test.js
- src/tests/Header.test.js
- src/tests/HeaderSearch.test.js
- src/tests/Login.test.js
- src/tests/RenderWithRouter.js
> mais alguns testes

- src/components/FavoriteButton.jsx
- src/components/ShareButton.jsx
- src/helpers/assets.js
- src/pages/FoodDetail.js
- src/pages/Perfil.js
- src/pages/RecipeInProgress.js
PR para atualizar main-group e fixar requisito 10
> atualizaçao de branch

- src/App.js
- src/components/AreaDropDown.js
- src/components/RecipeCard.js
- src/components/RecipesList.js
- src/pages/CockTail.js
- src/pages/ExploreDrinkByIngredients.js
- src/pages/ExploreFoodByArea.js
- src/pages/Food.js
- src/pages/FoodDetail.js
- src/pages/NotFound.js
- src/redux/actions/searchRecipes.js
- src/redux/reducers/searchRecipes.js
- src/redux/reducers/sitemap.js
adding req 78,79,80,81  adding foodbyarea and notfound page
> Main group 12 req78 explore food by area

- debug.log
- src/components/CardFavorite.jsx
- src/components/FavoriteShareButtons.jsx
- src/components/Footer.jsx
- src/context/ReceitasProvider.jsx
- src/pages/Comidas.jsx
- src/pages/IngredientsList.jsx
- src/pages/ListaIngredientesEmProgresso.jsx
- src/pages/ReceitaDetalhada.jsx
- src/pages/ReceitaEmProgresso.jsx
- src/pages/ReceitasFavoritas.jsx
- src/pages/ReceitasFeitas.jsx
> [GROUP - 20] dividindo

- src/components/ShareButton.jsx
- src/pages/RecipeInProgress.js
> adding requirements 51, 52, 53

- src/components/ShareButton.js
- src/pages/ExploreIngredient.js
- src/pages/FavoriteRecipes.js
- src/tests/08RecipesDoneTests/Requisite54-59.test.js
- src/tests/10ExploreTest/Requisite67-69.test.js
- src/tests/11ExploreFoodsOrDrinksTest/Requisite70-74.test.js
- src/tests/12ExploreIngredients/Requisite75-77.test.js
- src/tests/13ExploreLocalAreaTest/Requisite78-81.test.js
- src/tests/14PerfilTest/Requisite82-87.test.js
> test implementations

- src/components/CardFavorite.jsx
- src/components/FavoriteShareButtons.jsx
- src/pages/ReceitasFavoritas.jsx
- src/pages/ReceitasFeitas.jsx
- src/stylesCSS/Card.css
- src/stylesCSS/PageDetalhada.css
Corrigi os errinhos citados no Slack e terminei o CSS
> [GROUP - 20] ALL DONE

- src/pages/FavoriteRecipes.js
- src/tests/09FavoriteRecipesTest/Requisite60-66.test.js
Main group 24 test favorite recipes 60 66
> Main group 24 test favorite recipes 60 66

- src/tests/08RecipesDoneTests/Requisite54-59.test.js
Main group 24 test recipes done
> Main group 24 test recipes done

- src/tests/08RecipesDoneTests/Requisite54-59.test.js
Reverts tryber/sd-06-project-recipes-app#753
> Revert "Main group 24 test recipes done"
